classdef student
    properties
        id
        gender
        speed
        StartTime
        source
        dest
        loc
        last_node
        food_require
        floor
        left_elevator
        left_canteen_time
    end
    properties
        desitionG
    end
end